apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: api-demo1
spec:
  components:
    - name: api-demo1
      type: webservice
      properties:
        image: aichapterera/api-demo1:20250831201100
        port: 8000
        cmd: ["python", "src/api-v2.py"]
        env:
          - name: ENV
            value: "production"
        imagePullSecrets:             # 私有镜像凭证
          - name: api-demo1-dockerhub-secret
        expose: true                  # 关键：让 KubeVela 自动暴露 Service
      traits:
        - type: scaler
          properties:
            replicas: 2
        - type: rollout
          properties:
            policy: canary
            stepSize: 1
        - type: resources
          properties:
            cpu: "500m"
            memory: "512Mi"
