apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: api-demo1
  namespace: default
spec:
  components:
    - name: api-demo1
      type: webservice
      properties:
        image: aichapterera/api-demo1:20250901055456
        port: 8080
        cmd: ["python", "src/api-v2.py"]
        env:
          - name: ENV
            value: "production"
        expose: true                  # 关键：让 KubeVela 自动暴露 Service
      traits:
        - type: scaler
          properties:
            replicas: 2